alter table public.students add column if not exists photo_url text;
alter table public.students add column if not exists blood_group text;
alter table public.students add column if not exists address text;
alter table public.students add column if not exists joined_on date;
alter table public.students add column if not exists notes text;
alter table public.staff add column if not exists user_id uuid references auth.users(id);
alter table public.staff add column if not exists joined_on date;
alter table public.staff add column if not exists address text;
alter table public.staff add column if not exists qualification text;
create unique index if not exists staff_user_school_idx on public.staff(school_id,user_id) where user_id is not null;
create unique index if not exists teacher_assignment_unique_idx on public.teacher_assignments(staff_id,academic_year_id,class_id,coalesce(section_id,'00000000-0000-0000-0000-000000000000'::uuid));
create unique index if not exists teacher_subject_assignment_unique_idx on public.teacher_subject_assignments(staff_id,subject_id,academic_year_id,class_id,coalesce(section_id,'00000000-0000-0000-0000-000000000000'::uuid));
alter table public.timetable_entries add constraint timetable_valid_time check(ends_at>starts_at);
create index if not exists timetable_lookup_idx on public.timetable_entries(school_id,academic_year_id,class_id,section_id,weekday,starts_at);
drop policy if exists "manage homework" on public.homework;
create policy "manage homework" on public.homework for all to authenticated using(public.can_mark_academics(school_id)) with check(public.can_mark_academics(school_id));
drop policy if exists "manage timetable" on public.timetable_entries;
create policy "manage timetable" on public.timetable_entries for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal']::public.school_role[]));
drop policy if exists "manage tsa" on public.teacher_subject_assignments;
create policy "manage tsa" on public.teacher_subject_assignments for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal']::public.school_role[]));