-- Final privacy hardening + communication center.
create or replace function public.can_view_student(target_student uuid) returns boolean language sql stable security definer set search_path=public as $$ select (select auth.uid()) is not null and (exists(select 1 from public.students s where s.id=target_student and s.user_id=(select auth.uid())) or exists(select 1 from public.guardians g where g.student_id=target_student and g.user_id=(select auth.uid())) or exists(select 1 from public.students s join public.school_memberships m on m.school_id=s.school_id where s.id=target_student and m.user_id=(select auth.uid()) and m.active=true and m.role=any(array['school_owner','principal','teacher','accountant','reception']::public.school_role[]))); $$;
revoke all on function public.can_view_student(uuid) from public,anon;grant execute on function public.can_view_student(uuid) to authenticated;
drop policy if exists "students members read" on public.students;drop policy if exists "portal read student" on public.students;create policy "student authorized read" on public.students for select to authenticated using(public.can_view_student(id));
drop policy if exists "enrollments members read" on public.student_enrollments;create policy "enrollment authorized read" on public.student_enrollments for select to authenticated using(public.can_view_student(student_id));
drop policy if exists "members read guardians" on public.guardians;create policy "guardian authorized read" on public.guardians for select to authenticated using(public.can_view_student(student_id));
drop policy if exists "members read attendance" on public.student_attendance;drop policy if exists "portal read attendance" on public.student_attendance;create policy "attendance authorized read" on public.student_attendance for select to authenticated using(public.can_view_student(student_id));
drop policy if exists "read fee assignments" on public.student_fee_assignments;drop policy if exists "portal read fee assignments" on public.student_fee_assignments;create policy "fee assignment authorized read" on public.student_fee_assignments for select to authenticated using(public.can_manage_finance(school_id) or public.can_view_student(student_id));
drop policy if exists "read payments" on public.fee_payments;drop policy if exists "portal read fee payments" on public.fee_payments;create policy "payment authorized read" on public.fee_payments for select to authenticated using(public.can_manage_finance(school_id) or public.can_view_student(student_id));
drop policy if exists "portal read exam marks" on public.exam_marks;drop policy if exists "read marks" on public.exam_marks;create policy "marks authorized read" on public.exam_marks for select to authenticated using(public.can_mark_academics(school_id) or (public.can_view_student(student_id) and exists(select 1 from public.exam_subjects es join public.exams e on e.id=es.exam_id where es.id=exam_subject_id and e.published=true)));
create table public.communication_campaigns(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,title text not null,body text not null,audience text not null check(audience in('school','staff','parents','students','class')),class_id uuid references public.classes(id),section_id uuid references public.sections(id),status text not null default 'sent' check(status in('draft','sent','cancelled')),created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),sent_at timestamptz);
alter table public.communication_campaigns enable row level security;
create policy "staff read campaigns" on public.communication_campaigns for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','teacher','accountant','reception']::public.school_role[]));
create policy "manage campaigns" on public.communication_campaigns for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));