-- Library and transport operational modules.
create table public.library_books(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,isbn text,title text not null,author text,publisher text,category text,total_copies integer not null default 1 check(total_copies>=0),available_copies integer not null default 1 check(available_copies>=0 and available_copies<=total_copies),shelf text,active boolean not null default true,created_at timestamptz not null default now());
create table public.library_loans(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,book_id uuid not null references public.library_books(id),student_id uuid not null references public.students(id),issued_on date not null default current_date,due_on date not null,returned_on date,status text not null default 'issued' check(status in('issued','returned','lost')),issued_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.transport_routes(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,name text not null,vehicle_no text,driver_name text,driver_phone text,monthly_fee numeric(12,2) not null default 0 check(monthly_fee>=0),active boolean not null default true,created_at timestamptz not null default now(),unique(school_id,name));
create table public.transport_stops(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,route_id uuid not null references public.transport_routes(id) on delete cascade,name text not null,pickup_time time,drop_time time,sort_order integer not null default 0);
create table public.student_transport(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,route_id uuid not null references public.transport_routes(id),stop_id uuid references public.transport_stops(id),academic_year_id uuid not null references public.academic_years(id),active boolean not null default true,created_at timestamptz not null default now(),unique(student_id,academic_year_id));
alter table public.library_books enable row level security;alter table public.library_loans enable row level security;alter table public.transport_routes enable row level security;alter table public.transport_stops enable row level security;alter table public.student_transport enable row level security;
create policy "school read books" on public.library_books for select to authenticated using(public.is_school_member(school_id));
create policy "manage books" on public.library_books for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));
create policy "authorized loans read" on public.library_loans for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','teacher','reception']::public.school_role[]) or public.can_view_student(student_id));
create policy "manage loans" on public.library_loans for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));
create policy "school read routes" on public.transport_routes for select to authenticated using(public.is_school_member(school_id));
create policy "manage routes" on public.transport_routes for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));
create policy "school read stops" on public.transport_stops for select to authenticated using(public.is_school_member(school_id));
create policy "manage stops" on public.transport_stops for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));
create policy "authorized transport read" on public.student_transport for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','teacher','accountant','reception']::public.school_role[]) or public.can_view_student(student_id));
create policy "manage student transport" on public.student_transport for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));

create or replace function public.issue_library_book(p_school_id uuid,p_book_id uuid,p_student_id uuid,p_due_on date) returns uuid language plpgsql security invoker set search_path=public as $$declare bid uuid;begin
 if not public.has_school_role(p_school_id,array['school_owner','principal','reception']::public.school_role[]) then raise exception 'Not authorized';end if;
 update public.library_books set available_copies=available_copies-1 where id=p_book_id and school_id=p_school_id and available_copies>0 returning id into bid;
 if bid is null then raise exception 'Book is unavailable';end if;
 insert into public.library_loans(school_id,book_id,student_id,due_on,issued_by) values(p_school_id,p_book_id,p_student_id,p_due_on,(select auth.uid())) returning id into bid;return bid;end;$$;
create or replace function public.return_library_book(p_school_id uuid,p_loan_id uuid) returns void language plpgsql security invoker set search_path=public as $$declare b uuid;begin
 if not public.has_school_role(p_school_id,array['school_owner','principal','reception']::public.school_role[]) then raise exception 'Not authorized';end if;
 update public.library_loans set status='returned',returned_on=current_date where id=p_loan_id and school_id=p_school_id and status='issued' returning book_id into b;if b is null then raise exception 'Active loan not found';end if;
 update public.library_books set available_copies=least(total_copies,available_copies+1) where id=b;end;$$;
revoke all on function public.issue_library_book(uuid,uuid,uuid,date) from public,anon;grant execute on function public.issue_library_book(uuid,uuid,uuid,date) to authenticated;
revoke all on function public.return_library_book(uuid,uuid) from public,anon;grant execute on function public.return_library_book(uuid,uuid) to authenticated;