-- Assets/inventory, staff leave and school calendar.
create table public.asset_categories(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,name text not null,created_at timestamptz not null default now(),unique(school_id,name));
create table public.assets(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,category_id uuid references public.asset_categories(id),asset_code text not null,name text not null,quantity integer not null default 1 check(quantity>=0),location text,purchase_date date,purchase_cost numeric(12,2) check(purchase_cost is null or purchase_cost>=0),condition text not null default 'good' check(condition in('new','good','fair','repair','retired')),notes text,active boolean not null default true,created_at timestamptz not null default now(),unique(school_id,asset_code));
create table public.staff_leave_requests(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,staff_id uuid not null references public.staff(id) on delete cascade,leave_type text not null,start_date date not null,end_date date not null,reason text not null,status text not null default 'pending' check(status in('pending','approved','rejected','cancelled')),requested_by uuid not null references auth.users(id),reviewed_by uuid references auth.users(id),reviewed_at timestamptz,review_note text,created_at timestamptz not null default now(),check(end_date>=start_date));
create table public.school_calendar_events(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,title text not null,event_type text not null default 'event' check(event_type in('holiday','event','exam','meeting','activity')),starts_on date not null,ends_on date not null,description text,audience text not null default 'school' check(audience in('school','staff','students','parents')),created_by uuid references auth.users(id),created_at timestamptz not null default now(),check(ends_on>=starts_on));
alter table public.asset_categories enable row level security;alter table public.assets enable row level security;alter table public.staff_leave_requests enable row level security;alter table public.school_calendar_events enable row level security;
create policy "staff read asset categories" on public.asset_categories for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','accountant','reception']::public.school_role[]));
create policy "manage asset categories" on public.asset_categories for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[]));
create policy "staff read assets" on public.assets for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','accountant','reception']::public.school_role[]));
create policy "manage assets" on public.assets for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[]));
create policy "leave authorized read" on public.staff_leave_requests for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal']::public.school_role[]) or requested_by=(select auth.uid()));
create policy "staff request own leave" on public.staff_leave_requests for insert to authenticated with check(requested_by=(select auth.uid()) and exists(select 1 from public.staff st where st.id=staff_id and st.school_id=school_id and st.user_id=(select auth.uid())));
create policy "leaders review leave" on public.staff_leave_requests for update to authenticated using(public.has_school_role(school_id,array['school_owner','principal']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal']::public.school_role[]));
create policy "calendar school read" on public.school_calendar_events for select to authenticated using(public.is_school_member(school_id));
create policy "calendar manage" on public.school_calendar_events for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));
create index assets_school_category_idx on public.assets(school_id,category_id);create index leave_school_status_idx on public.staff_leave_requests(school_id,status,start_date);create index calendar_school_dates_idx on public.school_calendar_events(school_id,starts_on,ends_on);