-- Admissions CRM, expenses, branding and certificate registry.
alter table public.schools add column if not exists website text;alter table public.schools add column if not exists logo_path text;alter table public.schools add column if not exists principal_name text;alter table public.schools add column if not exists timezone text not null default 'Asia/Kolkata';
create table public.admission_enquiries(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,student_name text not null,guardian_name text,phone text not null,email text,class_interest text,source text,status text not null default 'new' check(status in('new','contacted','follow_up','converted','closed')),next_follow_up date,notes text,assigned_to uuid references public.staff(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.school_expenses(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,expense_date date not null,category text not null,description text not null,amount numeric(12,2) not null check(amount>0),payment_method text not null,reference_no text,vendor text,recorded_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.issued_certificates(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,student_id uuid not null references public.students(id),certificate_no text not null,certificate_type text not null check(certificate_type in('bonafide','study','transfer','conduct','other')),purpose text,issued_on date not null default current_date,issued_by uuid references auth.users(id),status text not null default 'issued' check(status in('issued','cancelled')),created_at timestamptz not null default now(),unique(school_id,certificate_no));
alter table public.admission_enquiries enable row level security;alter table public.school_expenses enable row level security;alter table public.issued_certificates enable row level security;
create policy "crm read" on public.admission_enquiries for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));create policy "crm manage" on public.admission_enquiries for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));
create policy "expense read" on public.school_expenses for select to authenticated using(public.can_manage_finance(school_id));create policy "expense manage" on public.school_expenses for all to authenticated using(public.can_manage_finance(school_id)) with check(public.can_manage_finance(school_id));
create policy "certificate authorized read" on public.issued_certificates for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]) or public.can_view_student(student_id));create policy "certificate manage" on public.issued_certificates for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));
create index enquiry_school_status_idx on public.admission_enquiries(school_id,status,next_follow_up);create index expense_school_date_idx on public.school_expenses(school_id,expense_date);create index certificate_student_idx on public.issued_certificates(student_id,issued_on);
drop policy if exists "owner updates school" on public.schools;create policy "owner updates school" on public.schools for update to authenticated using(public.has_school_role(id,array['school_owner']::public.school_role[])) with check(public.has_school_role(id,array['school_owner']::public.school_role[]));