-- HR/payroll, staff attendance, health, visitors and tenant module controls.
create table public.school_modules(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,module_key text not null,enabled boolean not null default true,updated_at timestamptz not null default now(),unique(school_id,module_key));
create table public.staff_attendance(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,staff_id uuid not null references public.staff(id) on delete cascade,attendance_date date not null,status text not null check(status in('present','absent','late','leave','half_day')),check_in time,check_out time,remarks text,marked_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(staff_id,attendance_date));
create table public.salary_structures(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,staff_id uuid not null unique references public.staff(id) on delete cascade,basic numeric(12,2) not null default 0 check(basic>=0),allowances numeric(12,2) not null default 0 check(allowances>=0),deductions numeric(12,2) not null default 0 check(deductions>=0),effective_from date not null default current_date,updated_at timestamptz not null default now());
create table public.payroll_runs(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,pay_month date not null,status text not null default 'draft' check(status in('draft','finalized','paid')),created_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(school_id,pay_month));
create table public.payroll_items(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,payroll_run_id uuid not null references public.payroll_runs(id) on delete cascade,staff_id uuid not null references public.staff(id),basic numeric(12,2) not null,allowances numeric(12,2) not null,deductions numeric(12,2) not null,net_pay numeric(12,2) not null,status text not null default 'pending' check(status in('pending','paid')),paid_on date,reference_no text,unique(payroll_run_id,staff_id));
create table public.student_health_records(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,blood_group text,allergies text,medical_conditions text,medications text,emergency_notes text,last_checkup date,updated_by uuid references auth.users(id),updated_at timestamptz not null default now(),unique(student_id));
create table public.visitor_entries(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,visitor_name text not null,phone text,purpose text not null,person_to_meet text,id_reference text,check_in timestamptz not null default now(),check_out timestamptz,gate_pass_no text not null,recorded_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(school_id,gate_pass_no));
alter table public.school_modules enable row level security;alter table public.staff_attendance enable row level security;alter table public.salary_structures enable row level security;alter table public.payroll_runs enable row level security;alter table public.payroll_items enable row level security;alter table public.student_health_records enable row level security;alter table public.visitor_entries enable row level security;
create policy "modules read" on public.school_modules for select to authenticated using(public.is_school_member(school_id));create policy "modules manage" on public.school_modules for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal']::public.school_role[]));
create policy "staff attendance read" on public.staff_attendance for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','accountant','reception']::public.school_role[]) or exists(select 1 from public.staff st where st.id=staff_id and st.user_id=(select auth.uid())));create policy "staff attendance manage" on public.staff_attendance for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));
create policy "salary read" on public.salary_structures for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[]) or exists(select 1 from public.staff st where st.id=staff_id and st.user_id=(select auth.uid())));create policy "salary manage" on public.salary_structures for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[]));
create policy "payroll runs finance" on public.payroll_runs for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[]));
create policy "payroll items read" on public.payroll_items for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[]) or exists(select 1 from public.staff st where st.id=staff_id and st.user_id=(select auth.uid())));create policy "payroll items finance manage" on public.payroll_items for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','accountant']::public.school_role[]));
create policy "health authorized read" on public.student_health_records for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','teacher','reception']::public.school_role[]) or public.can_view_student(student_id));create policy "health manage" on public.student_health_records for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));
create policy "visitor staff read" on public.visitor_entries for select to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));create policy "visitor manage" on public.visitor_entries for all to authenticated using(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[])) with check(public.has_school_role(school_id,array['school_owner','principal','reception']::public.school_role[]));
create index staff_attendance_date_idx on public.staff_attendance(school_id,attendance_date);create index payroll_month_idx on public.payroll_runs(school_id,pay_month);create index visitors_open_idx on public.visitor_entries(school_id,check_out,check_in);
insert into public.school_modules(school_id,module_key) select s.id,k from public.schools s cross join unnest(array['academics','fees','exams','communications','library','transport','assets','hr_payroll','health','visitors']) k on conflict do nothing;